// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAMWqZ7a1IWI36gNIDxstV6NoAk1-t1c-I',
    appId: '1:444958857569:web:2543312c31491132e60d20',
    messagingSenderId: '444958857569',
    projectId: 'elective-663a7',
    authDomain: 'elective-663a7.firebaseapp.com',
    storageBucket: 'elective-663a7.firebasestorage.app',
    measurementId: 'G-ZX38VRJD4W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCEPf76f4YKqPZoHAUWxHrKu94BAl7odyA',
    appId: '1:444958857569:android:ec89972bcba99ef9e60d20',
    messagingSenderId: '444958857569',
    projectId: 'elective-663a7',
    storageBucket: 'elective-663a7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBYwksBuiavJe07d6L8-q7_okAfPOG_RWY',
    appId: '1:444958857569:ios:f345458771e3b9dae60d20',
    messagingSenderId: '444958857569',
    projectId: 'elective-663a7',
    storageBucket: 'elective-663a7.firebasestorage.app',
    iosBundleId: 'com.example.faceRecognitionWithImages',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBYwksBuiavJe07d6L8-q7_okAfPOG_RWY',
    appId: '1:444958857569:ios:f345458771e3b9dae60d20',
    messagingSenderId: '444958857569',
    projectId: 'elective-663a7',
    storageBucket: 'elective-663a7.firebasestorage.app',
    iosBundleId: 'com.example.faceRecognitionWithImages',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAMWqZ7a1IWI36gNIDxstV6NoAk1-t1c-I',
    appId: '1:444958857569:web:0f59d277e0c3eca1e60d20',
    messagingSenderId: '444958857569',
    projectId: 'elective-663a7',
    authDomain: 'elective-663a7.firebaseapp.com',
    storageBucket: 'elective-663a7.firebasestorage.app',
    measurementId: 'G-6QJ1ZVHT2L',
  );
}
